enum MediumType {
  MANUSCRIPT
  PRINT
  ELECTRONIC
}

type ChapterCollation @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String
  media: [Medium] @manyToMany(relationName: "MediumChapterCollation")
  chapter: String
}

type Token @model @auth(rules: [{allow: public}]) {
  id: ID!
  lineID: ID! @index(name: "byLine")
  raw: String!
  state: String
  orderInLine: Int!
  orderInPage: String
}

type Line @model @auth(rules: [{allow: public}]) {
  id: ID!
  textElementID: ID! @index(name: "byTextElement")
  tokens: [Token] @hasMany(indexName: "byLine", fields: ["id"])
  order: Int
  region: [Int]
  text: String
}

type TextElement @model @auth(rules: [{allow: public}]) {
  id: ID!
  pageID: ID! @index(name: "byPage")
  lines: [Line] @hasMany(indexName: "byTextElement", fields: ["id"])
  order: Int
  position: String
  region: [Int]
}

type ImageElement @model @auth(rules: [{allow: public}]) {
  id: ID!
  pageID: ID! @index(name: "byPage")
  legend: TextElement @hasOne
  depictsUnitID: ID! @index(name: "byUnit")
  position: String
  order: Int
  location: [Int]
  motifs: [String]
  style: [String]
  region: [Int]
}

type Page @model @auth(rules: [{allow: public}]) {
  id: ID!
  mediumID: ID! @index(name: "byMedium")
  textElements: [TextElement] @hasMany(indexName: "byPage", fields: ["id"])
  imageElements: [ImageElement] @hasMany(indexName: "byPage", fields: ["id"])
  number: Int!
  pagination: Int
  foliation: String
  tags: [String]
  image: String
}

type Medium @model @auth(rules: [{allow: public}]) {
  id: ID!
  bookID: ID! @index(name: "byBook")
  pages: [Page] @hasMany(indexName: "byMedium", fields: ["id"])
  segments: [Segment] @hasMany(indexName: "byMedium", fields: ["id"])
  chapterCollations: [ChapterCollation] @manyToMany(relationName: "MediumChapterCollation")
  editor: String
  siglum: String
  type: MediumType
}

type Segment @model @auth(rules: [{allow: public}]) {
  id: ID!
  mediumID: ID! @index(name: "byMedium")
  unitID: ID! @index(name: "byUnit")
  type: String
  tags: [String]
  start: [Int!]
  end: [Int]
  lacuna: Boolean
}

type Unit @model @auth(rules: [{allow: public}]) {
  id: ID!
  bookID: ID! @index(name: "byBook")
  images: [ImageElement] @hasMany(indexName: "byUnit", fields: ["id"])
  segments: [Segment] @hasMany(indexName: "byUnit", fields: ["id"])
  title: String!
  order: [Int!]
  variant: String
  divider: Boolean
  topics: [String]
  motifs: [String]
  commentary: String
}

type Book @model @auth(rules: [{allow: public}]) {
  id: ID!
  siglum: String!
  title: String
  author: String
  authorDeathYear: Int
  media: [Medium] @hasMany(indexName: "byBook", fields: ["id"])
  units: [Unit] @hasMany(indexName: "byBook", fields: ["id"])
  editor: String
}
 