# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules

type Book @model @auth(rules: [{ allow: private }]) {
  id: ID! @primaryKey
  editor: String
  siglum: String! @index(name: "bySiglum")
  title: String
  author: String
  authorDeathYear: String
  media: [Medium] @hasMany
  units: [Unit] @hasMany
}

type Unit @model @auth(rules: [{ allow: private }]) {
  id: ID! @primaryKey
  parentID: ID @index(name: "byParent")
  parent: Unit @belongsTo(fields: ["parentID"])
  title: String!
  order: Int!
  frame: String @index(name: "byFrame")
  variant: String
  divider: Boolean
  commentary: String
  motifs: [String]
  topics: [String]
  children: [Unit] @hasMany(indexName: "byParent", fields: ["id"])
  segments: [Segment] @hasMany(indexName: "segmentByUnit", fields: ["id"])
  images: [ImageElement] @hasMany(indexName: "imageByUnit", fields: ["id"])
}

enum MediaFormat {
  MANUSCRIPT
  PRINT
  DIGITAL
}

type Medium @model @auth(rules: [{ allow: private }]) {
  id: ID! @primaryKey
  editor: String
  siglum: String! @index(name: "bySiglum")
  format: MediaFormat
  pages: [Page] @hasMany(indexName: "pageByMedium", fields: ["id"])
  segments: [Segment] @hasMany(indexName: "segmentByMedium", fields: ["id"])
}

type Page @model @auth(rules: [{ allow: private }]) {
  id: ID! @primaryKey
  mediumID: ID @index(name: "pageByMedium")
  medium: Medium @belongsTo(fields: ["mediumID"])
  number: Int! @index(name: "byNumber")
  pagination: Int
  foliation: String
  tags: [String]
  image: String
  commentary: [String]
  text: [TextElement] @hasMany(indexName: "textByPage", fields: ["id"])
  images: [ImageElement] @hasMany(indexName: "imageByPage", fields: ["id"])
}

type TextElement @model @auth(rules: [{ allow: private }]) {
  id: ID! @primaryKey
  pageID: ID @index(name: "textByPage")
  page: Page @belongsTo(fields: ["pageID"])
  order: Int
  position: String
  region: [Int]
  lines: [Line] @hasMany(indexName: "byElement", fields: ["id"])
}

type Line @model @auth(rules: [{ allow: private }]) {
  id: ID! @primaryKey
  elementID: ID @index(name: "byElement")
  order: Int
  region: [Int]
  tokens: [String]
  states: [String]
}

type ImageElement @model @auth(rules: [{ allow: private }]) {
  id: ID! @primaryKey
  pageID: ID @index(name: "imageByPage")
  page: Page @belongsTo(fields: ["pageID"])
  unitID: ID @index(name: "imageByUnit")
  unit: Unit @belongsTo(fields: ["unitID"])
  order: Int!
  position: String
  region: [Int]
  location: [Int]
  motifs: [String]
  style: [String]
  legend: TextElement @hasOne
}

type Segment @model @auth(rules: [{ allow: private }]) {
  id: ID! @primaryKey
  mediumID: ID @index(name: "segmentByMedium")
  medium: Medium @belongsTo(fields: ["mediumID"])
  unitID: ID @index(name: "segmentByUnit")
  unit: Unit @belongsTo(fields: ["unitID"])
  lacuna: Boolean
  type: String
  tags: [String]
  startPage: Int! @index(name: "ByStartPage")
  startLine: Int
  startToken: Int
  endPage: Int @index(name: "ByEndPage")
  endLine: Int
  endToken: Int
}

type ChapterCollation @model @auth(rules: [{ allow: private }]) {
  id: ID! @primaryKey
  editor: String
  name: String
  chapter: String
  media: [Medium] @hasMany
}

type Query {
  myCustomQuery(args: String): String @function(name: "rustMuhaqiqHandlerDEV")
}
