/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "eu-central-1",
  aws_appsync_graphqlEndpoint:
    "https://wcab44j3n5aifoy6hw6bifvzlm.appsync-api.eu-central-1.amazonaws.com/graphql",
  aws_appsync_region: "eu-central-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-35jcj5lqhjawnbmknomqc5kqru",
  aws_cognito_identity_pool_id:
    "eu-central-1:a6f002b7-6ea1-464b-94c5-c1ad616ebdb4",
  aws_cognito_region: "eu-central-1",
  aws_user_pools_id: "eu-central-1_SX4aJcI9D",
  aws_user_pools_web_client_id: "4d9bijb1m1qbc38qdd5tbfoknl",
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: [
    "EMAIL",
    "FAMILY_NAME",
    "GIVEN_NAME",
    "PREFERRED_USERNAME",
    "PICTURE",
  ],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_user_files_s3_bucket: "muhaqqiqkalilabucket90843-dev",
  aws_user_files_s3_bucket_region: "eu-central-1",
};

export default awsmobile;
